name: SComatic
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - bedtools=2.31.0=hf5e1c6e_3
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - brotli=1.1.0=hd590300_0
  - brotli-bin=1.1.0=hd590300_0
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py37h43b0acd_1
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - conda=4.12.0=py37h89c1867_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - cryptography=38.0.2=py37h38fbfac_1
  - curl=7.68.0=hf8cf82a_0
  - datamash=1.1.0=0
  - expat=2.5.0=hcb278e6_1
  - fontconfig=2.14.2=h14ed4e7_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=h47867f9_33
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=7.5.0=h56cb351_20
  - gfortran_linux-64=7.5.0=h78c8a43_33
  - glib=2.78.0=hfc55251_0
  - glib-tools=2.78.0=hfc55251_0
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.5=h294904e_1
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h555fc39_33
  - harfbuzz=2.4.0=h9f30f68_3
  - htslib=1.10.2=h78d89cc_0
  - icu=64.2=he1b5a44_1
  - idna=3.4=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=8_openblas
  - libbrotlicommon=1.1.0=hd590300_0
  - libbrotlidec=1.1.0=hd590300_0
  - libbrotlienc=1.1.0=hd590300_0
  - libcblas=3.9.0=8_openblas
  - libcurl=7.68.0=hda55be3_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_1
  - libgfortran-ng=7.5.0=h14aa051_20
  - libgfortran4=7.5.0=h14aa051_20
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=8_openblas
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.39=h753d276_0
  - libsolv=0.7.24=hfc55251_4
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=h7e041cc_1
  - libtiff=4.2.0=hf544144_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.9.10=hee79883_0
  - libzlib=1.2.13=hd590300_5
  - make=4.3=hd18ef5c_1
  - mamba=0.1.2=py37h99015e2_0
  - ncurses=6.2=h58526e2_4
  - openssl=1.1.1w=hd590300_0
  - pango=1.42.4=h7062337_4
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.40=hc3806b6_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.38.0=h516909a_1003
  - pthread-stubs=0.4=h36c2ea0_1001
  - pycosat=0.6.4=py37h540881e_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py37h89c1867_5
  - python=3.7.12=hb7a2778_100_cpython
  - python_abi=3.7=4_cp37m
  - r-base=3.6.1=h3a67422_6
  - readline=8.1=h46c0cb4_0
  - requests=2.31.0=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py37h540881e_1007
  - samtools=1.10=h2e538c0_3
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sqlite=3.37.0=h9cd32fc_0
  - sysroot_linux-64=2.12=he073ed8_16
  - tk=8.6.12=h27826a3_0
  - tktable=2.10=h0c5db8f_3
  - urllib3=2.0.3=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - zstandard=0.18.0=py37h540881e_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - about-time==3.1.1
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - numpy==1.21.6
      - numpy-groupies==0.9.14
      - pandas==1.3.5
      - pybedtools==0.8.1
      - pysam==0.16.0.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - rpy2==2.9.4
      - scipy==1.7.3
      - six==1.16.0
prefix: /home/feng/miniconda3/envs/SComatic
