name: jupyter_renv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aiofiles=22.1.0=py311h06a4308_0
  - aiosqlite=0.18.0=py311h06a4308_0
  - anyio=3.5.0=py311h06a4308_0
  - archspec=0.2.2=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h5eee18b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py311h06a4308_0
  - babel=2.11.0=py311h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311h06a4308_0
  - binutils_impl_linux-64=2.40=hf600244_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - boltons=23.0.0=pyhd8ed1ab_0
  - brotli-python=1.1.0=py311hb755f60_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.21.0=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.16.0=py311hb3a22ac_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cmake=3.26.4=h96355d8_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=py311h06a4308_0
  - conda=23.10.0=py311h38be061_1
  - conda-libmamba-solver=23.11.0=pyhd8ed1ab_0
  - conda-package-handling=2.2.0=pyh38be061_0
  - conda-package-streaming=0.9.0=pyhd8ed1ab_0
  - curl=8.4.0=hca28451_0
  - debugpy=1.6.7=py311h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py311h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hcb278e6_1
  - fmt=10.1.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_2
  - gettext=0.21.1=h27087fc_0
  - gfortran_impl_linux-64=13.2.0=h76e1118_2
  - graphite2=1.3.13=h58526e2_1001
  - gxx_impl_linux-64=13.2.0=h338b0a0_2
  - harfbuzz=8.2.1=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - ipykernel=6.25.0=py311h92b7b1e_0
  - ipython=8.15.0=py311h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py311h06a4308_1
  - jinja2=3.1.2=py311h06a4308_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py311h38be061_3
  - jsonschema=4.19.2=py311h06a4308_0
  - jsonschema-specifications=2023.7.1=py311h06a4308_0
  - jupyter_client=7.4.9=py311h06a4308_0
  - jupyter_core=5.5.0=py311h06a4308_0
  - jupyter_events=0.8.0=py311h06a4308_0
  - jupyter_server=1.23.4=py311h06a4308_0
  - jupyter_server_fileid=0.9.0=py311h06a4308_0
  - jupyter_server_ydoc=0.8.0=py311h06a4308_1
  - jupyter_ydoc=0.2.4=py311h06a4308_0
  - jupyterlab=3.6.3=py311h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311h06a4308_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.7.2=h039dbb9_0
  - libblas=3.9.0=19_linux64_openblas
  - libcurl=8.4.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_2
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.1=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=19_linux64_openblas
  - libmamba=1.5.3=had39da4_1
  - libmambapy=1.5.3=py311hf2555c7_1
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsanitizer=13.2.0=h7e041cc_2
  - libsodium=1.0.18=h7b6447c_0
  - libsolv=0.7.26=hfc55251_0
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - make=4.3=hd18ef5c_1
  - mamba=1.5.3=py311h3072747_1
  - markupsafe=2.1.1=py311h5eee18b_0
  - matplotlib-inline=0.1.6=py311h06a4308_0
  - mistune=2.0.4=py311h06a4308_0
  - nbclassic=0.5.5=py311h06a4308_0
  - nbclient=0.8.0=py311h06a4308_0
  - nbconvert=7.10.0=py311h06a4308_0
  - nbformat=5.9.2=py311h06a4308_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.6=py311h06a4308_0
  - notebook=6.5.4=py311h06a4308_1
  - notebook-shim=0.2.3=py311h06a4308_0
  - openssl=3.1.4=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.14=ha41ecd1_2
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - pkg-config=0.29.2=h1bed415_8
  - platformdirs=3.10.0=py311h06a4308_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.14.1=py311h06a4308_0
  - prompt-toolkit=3.0.36=py311h06a4308_0
  - psutil=5.9.0=py311h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.6=py311h459d7ec_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=py311h06a4308_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311h06a4308_0
  - python-json-logger=2.0.7=py311h06a4308_0
  - python_abi=3.11=4_cp311
  - pytz=2023.3.post1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - pyzmq=23.2.0=py311h6a678d5_0
  - r-base=4.3.2=h93585b2_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=py311h06a4308_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=py311h06a4308_0
  - rfc3986-validator=0.1.1=py311h06a4308_0
  - rhash=1.4.3=hdbd6064_0
  - rpds-py=0.10.6=py311hb02cf49_0
  - ruamel.yaml=0.18.5=py311h459d7ec_0
  - ruamel.yaml.clib=0.2.7=py311h459d7ec_2
  - sed=4.8=he412f7d_0
  - send2trash=1.8.2=py311h06a4308_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py311h06a4308_1
  - soupsieve=2.5=py311h06a4308_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sysroot_linux-64=2.12=he073ed8_16
  - terminado=0.17.1=py311h06a4308_0
  - tinycss2=1.2.1=py311h06a4308_0
  - tk=8.6.13=noxft_h4845f30_101
  - tktable=2.10=h0c5db8f_5
  - tornado=6.3.3=py311h5eee18b_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py311h06a4308_0
  - truststore=0.8.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=py311h06a4308_0
  - typing_extensions=4.7.1=py311h06a4308_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311h06a4308_1
  - websocket-client=0.58.0=py311h06a4308_4
  - wheel=0.41.3=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.4.2=h5eee18b_0
  - y-py=0.5.9=py311h52d8a92_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.8.0=h59595ed_0
  - ypy-websocket=0.8.2=py311h06a4308_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.22.0=py311haa97af0_0
  - zstd=1.5.5=hfc55251_0
prefix: /home/feng/miniconda3/envs/jupyter_renv
